services:
  - type: web
    name: search_project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn search_project.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: search_project.settings
      - key: PYTHON_VERSION
        value: 3.12.6
